### PR TITLE
Merge Dialogue Graph

### PR DESCRIPTION
**Pull request by TheArchitect4855**
Created a dialogue graph editor.

### CODE REVIEW

**Review by JadenBalogh — COMMENTED** [review]
Overall looks really cool, awesome system!

Functionality ideas/comments:
 - When right-clicking an existing node, Create Node shouldn't be an option (instead, probably Create Transition at the top, then Delete Node below?)
 - One of the biggest features I would like to see would be the ability to pan the graph editor window (probably with middle click?)
 - Drag select/multi-select would be a nice feature
 - Selected node(s) should be visually indicated in the editor
 - I'd probably change some of the colors to make stuff more obvious at a glance: more distinctive entry and exit nodes, line color

Code style notes:
 - Namespace `Architect.Dialogue` should probably just be changed to `Dialogue` or similar. I like the idea of using namespaces for overarching systems though.
 - For the DialogueGraph asset menu item, it might look better *below* the create Folder option (i.e. order = 51)
 - We should use consistent code formatting for this project. If you pull the most recent from `dev`, you can use VSCode auto-format (Alt+Shift+F) in each file.

**Comment by TheArchitect4855** [comment]
Alright, I added most of the stuff you suggested except for multi-select (that's a challenge for another day) and formatting.

The formatter didn't do anything to my source code, so either it's all good or my formatter is broken.

**Review by JadenBalogh — COMMENTED** [review]
Quick work on the updates! Panning looks great and the context menus are perfect.

A couple other potential things I thought of while using it:
 - Showing the direction visually on transitions would be a really helpful addition (like the Animator)
 - Personal pet peeve: I hate when I can't deselect things - could we make it so that left-clicking not on a node deselects the current node?

Let's wait on merging until the code formatting is figured out. Doing that ASAP.

**Comment by TheArchitect4855** [comment]
1. I looked into making arrows initially, but apparently it's really difficult to do in the Unity editor. If you know of a good way, let me know :)
2. Done.

**Review by JadenBalogh — APPROVED** [review]
Awesome work on this tool! I updated the folder structure slightly and applied the code formatting to the added files. Approving this to be merged.

**Pull request merged**
